version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for snap's internal Go modules
  - package-ecosystem: "gomod"
    directory: "/snap/local/helper-go"
    schedule:
      interval: "daily"
