# Pre-define Devices
[[DeviceList]]
  Name = 'MQTT-test-device'
  ProfileName = 'Test.Device.MQTT.Profile'
  Description = 'MQTT device is created for test purpose'
  Labels = [ 'MQTT', 'test' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = 'tcp'
       Host = '0.0.0.0'
       Port = '1883'
       ClientId = 'CommandPublisher'
       Topic = 'CommandTopic'
       CredentialsPath = 'credentials'