[Incoming]
Protocol = "tcp"
Host = "0.0.0.0"
Port = 1883
Username = "admin"
Password = "public"
Qos = 0
KeepAlive = 3600
MqttClientId = "IncomingDataSubscriber"
Topic = "DataTopic"

[Response]
Protocol = "tcp"
Host = "0.0.0.0"
Port = 1883
Username = "admin"
Password = "public"
Qos = 0
KeepAlive = 3600
MqttClientId = "CommandResponseSubscriber"
Topic = "ResponseTopic"